# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.6
  - nightly
codecov: true
notifications:
  email: false
after_success:
  # push coverage results to Codecov
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate();
        using Coverage; Codecov.submit(Codecov.process_folder())';
jobs:
  include:
    - stage: "Documentation"
      julia: 1.6
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
